mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('notiteApp.urls', 'notiteApp'), namespace='notiteApp')),
    path('admin/', admin.site.urls),
]

mysite/notiteApp/urls.py
from django.urls import path

from . import views

app_name = 'notiteApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:id>', views.delete, name='delete'),
]

mysite/notiteApp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Note(models.Model):
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField()
    title = models.CharField(max_length=100)
    content = models.TextField()
    HIGH = 1
    MEDIUM = 2
    LOW = 3
    IMPORTANCE_CHOICES = (
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low'),
    )
    
    importance = models.IntegerField(choices=IMPORTANCE_CHOICES, default=3)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Note, self).save(*args, **kwargs)

mysite/notiteApp/views.py
from django.shortcuts import render, redirect
import datetime
from .models import Note

# Create your views here.
def index(request):
    context = {}
    notes = Note.objects.all()
    context['notes'] = notes
    return render(request, "notiteApp/home.html", context)

def add(request):
    context = {}

    if request.method == "POST":
        title = request.POST['note-title']
        content = request.POST['note-content']
        importance = request.POST['note-importance']

        note = Note(title=title, content=content, importance=importance)
        note.save()
        return redirect('notiteApp:index')

    return render(request, "notiteApp/add.html", context)

def delete(request, id):
    context = {}

    if request.method == "POST":
        note = Note.objects.get(id=id)
        note.delete()
        return redirect('notiteApp:index')

    return redirect('notiteApp:index')

mysite/notiteApp/templates/notiteApp/add.html
{% extends 'notiteApp/home.html' %}

{% block content %}

<h1 class="mt-5 mb-5 text-center">Add a new note</h1>

<form class="mx-auto mt-5" method="POST" action="{% url 'notiteApp:add' %}" id="note-form">
    {% csrf_token %}
    <div class="form-group mt-3">    
        <label for="note-title">Title:</label>
        <input class="form-control" type="text" placeholder="Title of note..." id="note-title" name="note-title">
    </div>
    <div class="form-group mt-3">
        <label for="note-content">Content:</label>
        <textarea class="form-control" name="note-content" id="note-content" form="note-form" placeholder="Enter text here..."></textarea>
    </div>
    <div class="form-group mt-3">
        <label for="note-importance">How important is this note:</label>
        <select class="form-control" name="note-importance" id="note-importance">
            <option value="">--Please choose the importance--</option>
            <option value="1">High</option>
            <option value="2">Medium</option>
            <option value="3">Low</option>
        </select>
    </div>
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-success mx-auto">Add note</button>
    </div>
</form>

{% endblock %}

mysite/notiteApp/templates/notiteApp/home.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static  'notiteApp/style.css' %}">
    <title>Notes</title>
    <meta name="viewport" content="width=device-width">
    <meta charset="utf-8">
    {% block extrahead %} {% endblock %}
</head>
<body>


    <!-- Navbar -->
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'notiteApp:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notiteApp:add' %}">Add note</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin page</a>
        </li>
      </ul>
  <!-- Navbar -->

  {% block content %}
      <h1 class="mt-5 mb-5 text-center">My notes</h1>

      {% if notes %}
        {% for note in notes %}
        <div class="card text-center mt-3 mx-auto">
            {% if note.importance == 1 %}
            <div class="card-header bg-danger">
              High importance!!!
            </div>
            {% endif %}
            {% if note.importance == 2 %}
            <div class="card-header bg-warning">
              Medium importance!
            </div>
            {% endif %}
            {% if note.importance == 3 %}
            <div class="card-header bg-info">
              Not so important
            </div>
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{note.title}}</h5>
              <p class="card-text">{{note.content}}</p>
            </div>
            <div class="card-footer text-muted row">
              {{note.created_at}}
              <form method="POST" action="{% url 'notiteApp:delete' note.id %}" id="delete-form">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-circle btn-sm">&minus;</button>
                </form>
            </div>
          </div>
        {% endfor %}
      {% endif %}

  {% endblock %}



</html>